// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/thumbnail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailRequest) Reset() {
	*x = ThumbnailRequest{}
	mi := &file_proto_thumbnail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequest) ProtoMessage() {}

func (x *ThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thumbnail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequest.ProtoReflect.Descriptor instead.
func (*ThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_proto_thumbnail_proto_rawDescGZIP(), []int{0}
}

func (x *ThumbnailRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

type ThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailResponse) Reset() {
	*x = ThumbnailResponse{}
	mi := &file_proto_thumbnail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailResponse) ProtoMessage() {}

func (x *ThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thumbnail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_proto_thumbnail_proto_rawDescGZIP(), []int{1}
}

func (x *ThumbnailResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ThumbnailResponse) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

var File_proto_thumbnail_proto protoreflect.FileDescriptor

const file_proto_thumbnail_proto_rawDesc = "" +
	"\n" +
	"\x15proto/thumbnail.proto\x12\tthumbnail\"/\n" +
	"\x10ThumbnailRequest\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\"B\n" +
	"\x11ThumbnailResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId2]\n" +
	"\x10ThumbnailService\x12I\n" +
	"\fGetThumbnail\x12\x1b.thumbnail.ThumbnailRequest\x1a\x1c.thumbnail.ThumbnailResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_thumbnail_proto_rawDescOnce sync.Once
	file_proto_thumbnail_proto_rawDescData []byte
)

func file_proto_thumbnail_proto_rawDescGZIP() []byte {
	file_proto_thumbnail_proto_rawDescOnce.Do(func() {
		file_proto_thumbnail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thumbnail_proto_rawDesc), len(file_proto_thumbnail_proto_rawDesc)))
	})
	return file_proto_thumbnail_proto_rawDescData
}

var file_proto_thumbnail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_thumbnail_proto_goTypes = []any{
	(*ThumbnailRequest)(nil),  // 0: thumbnail.ThumbnailRequest
	(*ThumbnailResponse)(nil), // 1: thumbnail.ThumbnailResponse
}
var file_proto_thumbnail_proto_depIdxs = []int32{
	0, // 0: thumbnail.ThumbnailService.GetThumbnail:input_type -> thumbnail.ThumbnailRequest
	1, // 1: thumbnail.ThumbnailService.GetThumbnail:output_type -> thumbnail.ThumbnailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_thumbnail_proto_init() }
func file_proto_thumbnail_proto_init() {
	if File_proto_thumbnail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thumbnail_proto_rawDesc), len(file_proto_thumbnail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thumbnail_proto_goTypes,
		DependencyIndexes: file_proto_thumbnail_proto_depIdxs,
		MessageInfos:      file_proto_thumbnail_proto_msgTypes,
	}.Build()
	File_proto_thumbnail_proto = out.File
	file_proto_thumbnail_proto_goTypes = nil
	file_proto_thumbnail_proto_depIdxs = nil
}
